apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "network-enforcer.fullname" . }}-controller
  labels:
  {{- include "network-enforcer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.security.rancher.io
  resources:
  - networkpolicyproposals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.security.rancher.io
  resources:
  - networkpolicyproposals/finalizers
  verbs:
  - update
- apiGroups:
  - security.security.rancher.io
  resources:
  - networkpolicyproposals/status
  verbs:
  - get
  - patch
  - update
