apiVersion: v1
kind: Service
metadata:
  name: otlp-receiver
  namespace: system
  labels:
    app.kubernetes.io/name: network-enforcer
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: network-enforcer
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
