//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicy) DeepCopyInto(out *WorkloadNetworkPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicy.
func (in *WorkloadNetworkPolicy) DeepCopy() *WorkloadNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadNetworkPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicyList) DeepCopyInto(out *WorkloadNetworkPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadNetworkPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicyList.
func (in *WorkloadNetworkPolicyList) DeepCopy() *WorkloadNetworkPolicyList {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadNetworkPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicyProposal) DeepCopyInto(out *WorkloadNetworkPolicyProposal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicyProposal.
func (in *WorkloadNetworkPolicyProposal) DeepCopy() *WorkloadNetworkPolicyProposal {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicyProposal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadNetworkPolicyProposal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicyProposalList) DeepCopyInto(out *WorkloadNetworkPolicyProposalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadNetworkPolicyProposal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicyProposalList.
func (in *WorkloadNetworkPolicyProposalList) DeepCopy() *WorkloadNetworkPolicyProposalList {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicyProposalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadNetworkPolicyProposalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicyProposalStatus) DeepCopyInto(out *WorkloadNetworkPolicyProposalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicyProposalStatus.
func (in *WorkloadNetworkPolicyProposalStatus) DeepCopy() *WorkloadNetworkPolicyProposalStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicyProposalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicySpec) DeepCopyInto(out *WorkloadNetworkPolicySpec) {
	*out = *in
	in.PolicyTemplate.DeepCopyInto(&out.PolicyTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicySpec.
func (in *WorkloadNetworkPolicySpec) DeepCopy() *WorkloadNetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}
