FROM registry.suse.com/bci/golang:1.26.5 AS builder
WORKDIR /src
COPY api/ /src/api
COPY cmd/ /src/cmd
COPY proto/ /src/proto
COPY internal/ /src/internal
COPY go.mod go.sum /src/
COPY Makefile /src/
RUN make cniwatcher

FROM scratch
WORKDIR /
COPY --from=builder /src/bin/cniwatcher /cniwatcher

USER 65532:65532
ENTRYPOINT ["/cniwatcher"]
